export const materials = [
  'Abdichtung Weber D2',
  'AIF',
  'AIF-OFF',
  'Akemi 2010 2K',
  'Akemi 2030 Dosen 2K',
  'Akemi 5010 Dosen 2K',
  'Akemi Imprägnierung',
  'Akemi QuickMix 2K',
  'Ardex Fugenmörtel',
  'Berner 2K Dübelkleber',
  'Bianco Iberico',
  'Bianco Sardo',
  'Coffee ',
  'Dichtband',
  'Elastorapid Mapei 2K',
  'Fliesenkleber Bio Flex',
  'Fließenkleber Bio Fast',
  'Fließenkleber Bio GEL',
  'Fürstensteiner',
  'FVE Imprägnierung',
  'Gisogrund PCI',
  'Grünes Band',
  'Impala',
  'Imperial Withe',
  'Ivory Fantasy',
  'Jura',
  'Keraquick Weiss',
  'Labrador Blue GT',
  'Natursteinsilikon',
  'Natursteinverlegemörtel NVM',
  'Nero Assoluto',
  'PCI Carrafug',
  'PCI Carrament',
  'PCI Flexoplast',
  'PCI Randdämmstreifen orange',
  'Quarzsand fein',
  'Quarzsand grob',
  'Rosa Beta',
  'Rosa Porino',
  'Schriftfarbe',
  'Shivakashi',
  'Silk Brown',
  'Steinrein  Reiniger',
  'Trasszement',
  'Travertin Noche'
];
